name: Canary Release on NPM

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/canary-release.yaml"
      - "config/build/**"
      - "scripts/**"
      - "src/**"
      - "package-lock.json"
      - "package.json"
      - "tsconfig.json"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ^22.5.0

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pin version
        run: |
          pkg_name="$(npm pkg get name | jq -r)"
          pkg_version="$(curl -s https://registry.npmjs.org/${pkg_name}/latest | jq -r .version)"

          npm --no-git-tag-version version "$pkg_version"
          npm --no-git-tag-version version minor

          pkg_version="$(npm pkg get version | jq -r)"

          npm --no-git-tag-version version "${pkg_version}-canary.$(date --utc +'%Y%m%dT%H%M%S')"

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: canary

  action-timeline:
    needs:
      - build-and-publish
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
