name: CI

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: npm ci

      - name: Format check
        run: npx dprint check

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: npm ci

      - name: Prepare for tsd
        run: mkdir dist && touch dist/index.d.ts

      - name: Type check
        run: mise run tsc

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: mise run lint

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: mise run test

  size-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: npm ci

      - name: Size check
        run: mise run size-check

  check-npm-token:
    runs-on: ubuntu-latest
    steps:
      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Verify NPM Token
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >~/.npmrc
          echo "✅ NPM token is valid. Logged in as: $(npm whoami || exit 1)"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  dry-run-npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: mise run build

      - name: Dry run publish to NPM
        run: npm publish --dry-run

  # e2e: {}

  action-timeline:
    needs:
      - format-check
      - type-check
      - lint
      - unit
      - size-check
      - check-npm-token
      - dry-run-npm-publish
      # - e2e
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
