name: Release on NPM

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">22.5.0"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pin version
        run: npm --no-git-tag-version version "${{ github.ref_name }}"

      - name: Set parameters
        id: params
        run: |
          ver="${{ github.ref_name }}"
          suf="${ver#*-}"
          pre=$([[ "$suf" == "$ver" ]] && echo false || echo true)
          echo "releaseTag=$($pre && echo "${suf%%.*}" || echo latest)" >> $GITHUB_OUTPUT
          echo "prerelease=$pre" >> $GITHUB_OUTPUT
          echo "makeLatest=$($pre && echo legacy || echo latest)" >> $GITHUB_OUTPUT

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: ${{ steps.params.outputs.releaseTag }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/tai-kun/use-machine-ts/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
          token: ${{ secrets.RELEASE_ACTION_GITHUB_TOKEN }}
          prerelease: ${{ steps.params.outputs.prerelease }}
          makeLatest: ${{ steps.params.outputs.makeLatest }}

  action-timeline:
    needs:
      - build-and-publish
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
