name: Release on NPM

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pin version
        run: npm --no-git-tag-version version "${GITHUB_REF#refs/*/}"

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

  release-on-github:
    runs-on: ubuntu-latest
    steps:
      - name: Get action parameters
        id: params
        run: |
          prerelease=$(echo ${{ github.ref_name }} | grep -q -E "v[0-9]+\.[0-9]+\.[0-9]+-.*" && echo true || echo false)
          echo ::set-output name=prerelease::$prerelease
          echo ::set-output name=makeLatest::$($prerelease && echo "legacy" || echo "latest")

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/tai-kun/use-machine-ts/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
          token: ${{ secrets.RELEASE_ACTION_GITHUB_TOKEN }}
          prerelease: ${{ steps.params.outputs.prerelease }}
          makeLatest: ${{ steps.params.outputs.makeLatest }}

  action-timeline:
    needs:
      - build-and-publish
      - release-on-github
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
