[tools]
node = "22"

[tasks.add]
run = "npx plop --plopfile .config/code/plopfile.mjs"

[tasks.fmt]
run = "npx dprint fmt"

[tasks.tsc]
run = [
  "npx tsc --noEmit",
  "npx tsd -f .config/env.d.ts -f 'src/**/*.{ts,tsx}'",
]

[tasks.lint]
run = "exit 0"

[tasks.test]
run = "npx vitest -c .config/vitest.config.ts src/"

[tasks.size-check]
depends = "build"
run = [
  "cd size-check && npm ci && npm run build",
  "npx size-limit",
]

[tasks.doc]
run = "npx typedoc src/index.ts"

[tasks.update]
run = [
  "mise upgrade",
  "npx npm-check-updates --cooldown 7 --target minor -u",
  "npm install",
  "npx dprint config update",
  "npm audit",
]
